name: myapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.1.0
  go_router: ^17.0.0
  provider: ^6.1.5+1
  google_fonts: ^6.1.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  google_sign_in: ^6.2.1
  cloudinary_public: ^0.23.1
  cached_network_image: ^3.4.1
  image_picker: ^1.2.1
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  google_maps_flutter: ^2.14.0
  intl: ^0.20.2
  share_plus: ^12.0.1
  firebase_storage: ^12.4.10
  url_launcher: ^6.3.2
  shared_preferences: ^2.5.3
  firebase_messaging: ^15.2.10
  equatable: ^2.0.7
  flutter_map: ^8.2.2
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.10.4

flutter:
  uses-material-design: true
